### ISSUE TITLE
Brainstorming & Todo

### ISSUE THREAD

**Issue by sveneberth** [mausbrand/flare#1]
- [ ] Network handler
- [ ] Event handler
- [ ] Priority queue
- [ ] Request handler?
- [ ] Ignite
  - [ ] embedsvg Icon manager (including reference generator)
  - [ ] Button
- [ ] More Popup dialogs
  - [ ] flare.popup.Error
  - [ ] flare.popup.Warning
  - [ ] flare.popup.Confirm
- [ ] ViUR Integration
  - [ ] Forms
  - [ ] Module handlers
    - [ ] Generic filters / search
    - [ ] List selector
    - [ ] Tree selector
    - [ ] Customizable Image / File uploader
